language: python 
python: 
- "3.6"
env: 
- DJANGO=2.0 DB=postgres
before_install: 
- cd decide
install: 
- pip install -r ../requirements.txt
before_script:
 - cp local_settings.travis.py local_settings.py
script: 
- python manage.py test