language: python 
python: 
- "3.6"
services:
- postgresql
env: 
- DJANGO=2.0 DB=postgres
global:
  - PGPORT=5432
before_install: 
- cd decide
install: 
- pip install -r ../requirements.txt
before_script: 
- cp local_settings.travis.py local_settings.py
- psql -c "create user decide with password 'decide'"
- psql -c "ALTER USER decide WITH SUPERUSER;"
- psql -c "create database decide owner decide"
script:
- python manage.py test postproc
before_deploy:
- zip elFile
deploy:
  provider: releases
  api_key: "6e6bdfb037e82a0231e42d330fb7c850e5a44b03"
  file: "elFile"
  skip_cleanup: true
  on:
    tags: true
addons:
  postgresql: "9.6"
