language: python 
python: 
- "3.6"
services:
- postgresql
env: 
- DJANGO=2.0 DB=postgres
global:
  - PGPORT=5432
  - RELEASE_NAME=foobar
before_install: 
- cd decide
install: 
- pip install -r ../requirements.txt
before_script: 
- cp local_settings.travis.py local_settings.py
- psql -c "create user decide with password 'decide'"
- psql -c "ALTER USER decide WITH SUPERUSER;"
- psql -c "create database decide owner decide"
script:
- python manage.py test postproc
before_deploy:
- mkdir files
- tar -czf $RELEASE_NAME.tar.gz files
- zip -r $RELEASE_NAME.zip files
- cd files
deploy:
    provider: releases
    api_key: 1a2de7ae8338f17e2e5512f60903ff7c628b48a1
    file: $RELEASE_NAME.zip
    skip_cleanup: true
    on:
        all_branches: true
addons:
  postgresql: "9.6"
