language: python 
python: 
- "3.6"
services:
- postgresql
env: 
- DJANGO=2.0 DB=postgres
global:
  - PGPORT=5432
  - RELEASE_NAME=foobar
before_install: 
- cd decide
install: 
- pip install -r ../requirements.txt
language: node_js
node_js: node
before_script: 
- cp local_settings.travis.py local_settings.py
- psql -c "create user decide with password 'decide'"
- psql -c "ALTER USER decide WITH SUPERUSER;"
- psql -c "create database decide owner decide"
script:
- python manage.py test postproc
before_deploy:
- rm -rf $RELEASE_NAME || exit 0
- mkdir $RELEASE_NAME
- cp LICENSE $RELEASE_NAME/
- cp -a ./static $RELEASE_NAME/
- cp -f build/*css $RELEASE_NAME/static/css/
- tar -czf $RELEASE_NAME-$TRAVIS_TAG.tar.gz $RELEASE_NAME
- zip -r $RELEASE_NAME-$TRAVIS_TAG.zip $RELEASE_NAME
deploy:
  provider: releases
  api_key: 
    secure: [redacted]
  file: foobar.zip
  skip_cleanup: true
  on:
    repo: manmacbec/Decide-Europa-Postproc
addons:
  postgresql: "9.6"
