language: python 
python: 
- "3.6"
services:
- postgresql
env: 
- DJANGO=2.0 DB=postgres
global:
  - PGPORT=5432
  - RELEASE_NAME=foobargi
before_install: 
- cd decide
install: 
- pip install -r ../requirements.txt
before_script: 
- cp local_settings.travis.py local_settings.py
- psql -c "create user decide with password 'decide'"
- psql -c "ALTER USER decide WITH SUPERUSER;"
- psql -c "create database decide owner decide"
script:
- python manage.py test postproc
before_deploy:
- rm -rf $RELEASE_NAME || exit 0
- mkdir $RELEASE_NAME
- cp LICENSE $RELEASE_NAME/
- cp -a ./static $RELEASE_NAME/
- cp -f build/*css $RELEASE_NAME/static/css/
- tar -czf $RELEASE_NAME.tar.gz $RELEASE_NAME
- zip -r $RELEASE_NAME.zip $RELEASE_NAME
deploy:
    provider: releases
    api_key: 1a2de7ae8338f17e2e5512f60903ff7c628b48a1
    file: $RELEASE_NAME.zip
    skip_cleanup: true
    on:
        repo: manmacbec/Decide-Europa-Postproc 
        tags: true
        all_branches: true
addons:
  postgresql: "9.6"
