language: python 
python: 
- "3.6"
env: 
- DJANGO=2.0 DB=postgres
before_install: 
- cd decide
install: 
- pip3 install -r ../requirements.txt
services:
  - postgresql
before_script:
 - cp local_settings.travis.py local_settings.py
 - psql -c "create user decide with password 'decide'" 
 - psql -c "create database decide owner decide"
 - python manage.py migrate
script: 
- python3 manage.py test